apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-hotel-dev

resources:
- ../../base
- namespace.yaml

patchesStrategicMerge:
- ingress-patch.yaml
- configmap-patch.yaml

images:
- name: openlabfree/globomantics-be:v7
  newName: ghcr.io/susmita-sharma/globomantics-hotel-backend
  newTag: 4a63a1fbfb23cda13cfc2637529710efb9f2108e
- name: openlabfree/globomantics-fe:v4
  newName: ghcr.io/susmita-sharma/globomantics-hotel-frontend
  newTag: 4a63a1fbfb23cda13cfc2637529710efb9f2108e
