apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-hotel-dev

resources:
- ../../base
- namespace.yaml
- tls-secret.yaml

patchesStrategicMerge:
- patches/ingress.yaml
- patches/configmap.yaml
- patches/namespace.yaml
- patches/frontend-deployment.yaml
- patches/backend-deployment.yaml

images:
- name: susmita-sharma/globomantics-be:v7
  newName: ghcr.io/susmita-sharma/globomantics-hotel-backend
  newTag: 4a63a1fbfb23cda13cfc2637529710efb9f2108e
- name: susmita-sharma/globomantics-fe:v4
  newName: ghcr.io/susmita-sharma/globomantics-hotel-frontend
  newTag: 4a63a1fbfb23cda13cfc2637529710efb9f2108e
