apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-backend-config
data:
  mongodb-host: "guestbook-database"
  mongodb-db-name: "guestbook"
  mongodb-db-param: "authSource=admin"
  s3-endpoint: "http://98.92.155.83:9000"
  s3-bucket: "visiting-cards"
  s3-region: "us-east-1"
  s3-use-ssl: "false"

# URI connection for standalone mongodb
#mongodb://admin:password@guestbook-database:/guestbook?authSource=admin
# URI connection for mongodb replicaset
#mongodb://admin:password@guestbook-database:/guestbook?authSource=admin&replicaSet=rs0
