apiVersion: v1
kind: Secret
metadata:
  name: guestbook-backend-secret 
data:
  mongodb-username: "YWRtaW4="
  mongodb-password: "cGFzc3dvcmQ="
  s3-access-key: "UkJZMDI5TzY0ODFKWUtTWldQWkkK"
  s3-secret-key: "V0thc0F1ZDRsc0l6ZXhHdEVUK0lTalJOdGIrUERqVzRHRE5ZdXQraQo="
